account kit some method added
Explore-In-HMS/common-mobile-services pull request #5
Opened 2022-01-04 13:43 UTC by berkeozkul

2022-01-06 11:09 UTC, omerakkus requested changes

2022-01-06 11:09 UTC, omerakkus commented on account/src/main/java/com/hms/lib/commonmobileservices/account/google/GoogleAccountServiceImpl.kt
> +    }
mGoogleSignInResult is not initialized. The function may not work correctly as a result of this variable returning null. Can you check again?

2022-01-06 11:09 UTC, omerakkus commented on account/src/main/java/com/hms/lib/commonmobileservices/account/google/GoogleAccountServiceImpl.kt
> +        return (mGoogleSignInResult as GoogleSignInResult).isSuccess
Can you check the same status in isSuccesful method? Additionally, can you correct the typo in the method? It should be **isSuccessful()**

2022-01-06 11:09 UTC, omerakkus commented on account/src/main/java/com/hms/lib/commonmobileservices/account/huawei/HuaweiAccountServiceImpl.kt
> +    override fun isSuccesful(): Boolean {
Can you correct the typo in the method? It should be **isSuccessful()**

2022-01-07 05:06 UTC, oguzozsoy commented on account/src/main/java/com/hms/lib/commonmobileservices/account/google/GoogleAccountServiceImpl.kt
> +        return (mGoogleSignInResult as GoogleSignInResult).signInAccount?.let { mapper.map(it) }
Did you test this method? mGoogleSignInResult has never been initialized it will be null.

2022-01-07 05:09 UTC, oguzozsoy commented on account/src/main/java/com/hms/lib/commonmobileservices/account/huawei/HuaweiAccountServiceImpl.kt
> +        return HuaweiIdAuthResult().isSuccess
You are calling a new instance of HuaweiIdAuthResult is its correct usage? Could you please check it?

2022-01-07 05:11 UTC, oguzozsoy commented on account/src/main/java/com/hms/lib/commonmobileservices/account/huawei/HuaweiAccountServiceImpl.kt
> +        return mapper.map(HuaweiIdAuthResult().huaweiId)
You are calling a new instance of HuaweiIdAuthResult is its correct usage? Could you please check it?

2022-01-07 05:20 UTC, oguzozsoy commented on account/src/main/java/com/hms/lib/commonmobileservices/account/huawei/HuaweiAccountServiceImpl.kt
> +            .addOnSuccessListener { worker.onSuccess(Unit) }
This seems you need to create a broadcast receiver to get SMS content. This usage is not correct. You can leave this feature to the new sprint.

2022-01-07 05:21 UTC, oguzozsoy requested changes
Please update PR according to comments.

2022-01-07 05:28 UTC, omerakkus requested changes

2022-01-07 05:28 UTC, omerakkus commented on account/src/main/java/com/hms/lib/commonmobileservices/account/google/GoogleAccountServiceImpl.kt
> +        mGoogleSmsRetriver.startSmsRetriever().addOnSuccessListener { worker.onSuccess(Unit) }
You need to create broadcast receiver to get content of the SMS. We can remove this feature from this sprint and do it in the next sprint. You need to examine in detail usage of the services.

2022-01-10 06:31 UTC, omerakkus approved these changes

2022-01-10 09:24 UTC, oguzozsoy approved these changes
it seems ok.

2022-01-10 09:24 UTC, merged