Map kit update
Explore-In-HMS/common-mobile-services pull request #7
Opened 2022-01-10 09:31 UTC by oguzozsoy

2022-01-11 07:58 UTC, oguzozsoy commented on mapkit/build.gradle
> -    api 'com.huawei.hms:maps:5.2.0.302'
please dont update the version

2022-01-11 14:02 UTC, omerakkus requested changes

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/CircleOptions.kt
>  }
Could you please add licenses for CircleOptions class?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/GroundOverlay.kt
> +}
Could you please add licenses for GroundOverlay class?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/GroundOverlayOptions.kt
> +package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses for GroundOverlayOptions class?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/LatLngBounds.kt
> +package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses ?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/TypeAliases.kt
>  typealias GmsCircle = com.google.android.gms.maps.model.Circle
Could you please add licenses for CircleOptions class?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/CircleOptions.kt
>  package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/Circle.kt
> +package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses ?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/Tile.kt
> +package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses ?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/TileOverlay.kt
> +package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses ?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/TileOverlayOptions.kt
> +package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses ?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/TileProvider.kt
> +package com.hms.lib.commonmobileservices.mapkit.model
Could you please add licenses ?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/TypeAliases.kt
>  typealias GmsGroundOverlayOptions = com.google.android.gms.maps.model.GroundOverlayOptions
Could you please add licenses ?

2022-01-11 14:02 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/LocationSource.kt
> +package com.hms.lib.commonmobileservices.mapkit
Could you please add licenses ?

2022-01-11 14:07 UTC, omerakkus commented on mapkit/src/main/java/com/hms/lib/commonmobileservices/mapkit/model/CircleOptions.kt
>  package com.hms.lib.commonmobileservices.mapkit.model
ok

2022-01-13 08:26 UTC, omerakkus approved these changes

2022-01-13 08:26 UTC, merged